INSERT INTO province (id, name) VALUES
                                    (1, 'Lai Châu'),
                                    (2, 'Điện Biên'),
                                    (3, 'Sơn La'),
                                    (4, 'Lạng Sơn'),
                                    (5, 'Quảng Ninh'),
                                    (6, 'Thanh Hóa'),
                                    (7, 'Nghệ An'),
                                    (8, 'Hà Tĩnh'),
                                    (9, 'Cao Bằng'),
                                    (10, 'Tuyên Quang'),
                                    (11, 'Lào Cai'),
                                    (12, 'Thái Nguyên'),
                                    (13, 'Phú Thọ'),
                                    (14, 'Bắc Ninh'),
                                    (15, 'Hưng Yên'),
                                    (16, 'Đắk Lắk'),
                                    (17, 'Đồng Nai'),
                                    (18, 'Tây Ninh'),
                                    (19, 'Vĩnh Long'),
                                    (20, 'Đồng Tháp'),
                                    (21, 'Cà Mau'),
                                    (22, 'An Giang'),
                                    (23, 'Quảng Bình'),
                                    (24, 'Quảng Trị'),
                                    (25, 'Quảng Nam'),
                                    (26, 'Quảng Ngãi'),
                                    (27, 'Bình Định'),
                                    (28, 'Khánh Hòa'),
                                    (29, 'Ninh Thuận'),
                                    (30, 'Bình Thuận'),
                                    (31, 'Bà Rịa - Vũng Tàu'),
                                    (32, 'Bình Dương');
INSERT INTO customer (first_name, last_name, province_id) VALUES
                                                              ('Nguyễn', 'Văn A', 1), ('Trần', 'Thị B', 2), ('Lê', 'Văn C', 3), ('Phạm', 'Thị D', 4),
                                                              ('Huỳnh', 'Minh E', 5), ('Vũ', 'Thị F', 6), ('Đặng', 'Văn G', 7), ('Bùi', 'Thị H', 8),
                                                              ('Đỗ', 'Quốc I', 9), ('Hồ', 'Mỹ K', 10), ('Dương', 'Văn L', 11), ('Hoàng', 'Thị M', 12),
                                                              ('Ngô', 'Quang N', 13), ('Mai', 'Thị O', 14), ('Tạ', 'Văn P', 15), ('Đinh', 'Thị Q', 16),
                                                              ('Lý', 'Văn R', 17), ('Trịnh', 'Thị S', 18), ('Châu', 'Minh T', 19), ('Cao', 'Thị U', 20),
                                                              ('Võ', 'Văn V', 21), ('Phan', 'Thị W', 22), ('Nguyễn', 'Thanh X', 23), ('Trần', 'Thị Y', 24),
                                                              ('Lê', 'Minh Z', 25), ('Phạm', 'Anh A1', 26), ('Huỳnh', 'Thị B1', 27), ('Vũ', 'Quốc C1', 28),
                                                              ('Đặng', 'Thị D1', 29), ('Bùi', 'Văn E1', 30), ('Đỗ', 'Thị F1', 31), ('Hồ', 'Quang G1', 32),
                                                              ('Dương', 'Mỹ H1', 1), ('Hoàng', 'Văn I1', 2), ('Ngô', 'Thị K1', 3), ('Mai', 'Văn L1', 4),
                                                              ('Tạ', 'Thị M1', 5), ('Đinh', 'Văn N1', 6), ('Lý', 'Thị O1', 7), ('Trịnh', 'Văn P1', 8),
                                                              ('Châu', 'Thị Q1', 9), ('Cao', 'Văn R1', 10), ('Võ', 'Thị S1', 11), ('Phan', 'Văn T1', 12),
                                                              ('Nguyễn', 'Minh U1', 13), ('Trần', 'Thị V1', 14), ('Lê', 'Văn W1', 15), ('Phạm', 'Thị X1', 16),
                                                              ('Huỳnh', 'Quốc Y1', 17), ('Vũ', 'Thị Z1', 18), ('Đặng', 'Văn A2', 19), ('Bùi', 'Thị B2', 20),
                                                              ('Đỗ', 'Anh C2', 21), ('Hồ', 'Thị D2', 22), ('Dương', 'Văn E2', 23), ('Hoàng', 'Thị F2', 24),
                                                              ('Nguyễn', 'Văn G2', 25), ('Trần', 'Thị H2', 26), ('Lê', 'Minh I2', 27), ('Phạm', 'Anh K2', 28),
                                                              ('Huỳnh', 'Thị L2', 29), ('Vũ', 'Quốc M2', 30), ('Đặng', 'Thị N2', 31), ('Bùi', 'Văn O2', 32),
                                                              ('Đỗ', 'Mỹ P2', 1), ('Hồ', 'Văn Q2', 2), ('Dương', 'Thị R2', 3), ('Hoàng', 'Văn S2', 4),
                                                              ('Nguyễn', 'Quang T2', 5), ('Trần', 'Thị U2', 6), ('Lê', 'Văn V2', 7), ('Phạm', 'Thị W2', 8),
                                                              ('Huỳnh', 'Minh X2', 9), ('Vũ', 'Thị Y2', 10), ('Đặng', 'Văn Z2', 11), ('Bùi', 'Thị A3', 12),
                                                              ('Đỗ', 'Quốc B3', 13), ('Hồ', 'Mỹ C3', 14), ('Dương', 'Văn D3', 15), ('Hoàng', 'Thị E3', 16),
                                                              ('Nguyễn', 'Văn F3', 17), ('Trần', 'Thị G3', 18), ('Lê', 'Minh H3', 19), ('Phạm', 'Anh I3', 20),
                                                              ('Huỳnh', 'Thị K3', 21), ('Vũ', 'Quốc L3', 22), ('Đặng', 'Thị M3', 23), ('Bùi', 'Văn N3', 24),
                                                              ('Đỗ', 'Mỹ O3', 25), ('Hồ', 'Văn P3', 26), ('Dương', 'Thị Q3', 27), ('Hoàng', 'Văn R3', 28),
                                                              ('Nguyễn', 'Quang S3', 29), ('Trần', 'Thị T3', 30), ('Lê', 'Văn U3', 31), ('Phạm', 'Thị V3', 32),
                                                              ('Huỳnh', 'Minh W3', 1), ('Vũ', 'Thị X3', 2), ('Đặng', 'Văn Y3', 3), ('Bùi', 'Thị Z3', 4),
                                                              ('Đỗ', 'Quốc A4', 5), ('Hồ', 'Mỹ B4', 6), ('Dương', 'Văn C4', 7), ('Hoàng', 'Thị D4', 8),
                                                              ('Nguyễn', 'Văn E4', 9), ('Trần', 'Thị F4', 10), ('Lê', 'Minh G4', 11), ('Phạm', 'Anh H4', 12),
                                                              ('Huỳnh', 'Thị I4', 13), ('Vũ', 'Quốc K4', 14), ('Đặng', 'Thị L4', 15), ('Bùi', 'Văn M4', 16),
                                                              ('Đỗ', 'Mỹ N4', 17), ('Hồ', 'Văn O4', 18), ('Dương', 'Thị P4', 19), ('Hoàng', 'Văn Q4', 20),
                                                              ('Nguyễn', 'Quang R4', 21), ('Trần', 'Thị S4', 22), ('Lê', 'Văn T4', 23), ('Phạm', 'Thị U4', 24),
                                                              ('Huỳnh', 'Minh V4', 25), ('Vũ', 'Thị W4', 26), ('Đặng', 'Văn X4', 27), ('Bùi', 'Thị Y4', 28),
                                                              ('Đỗ', 'Quốc Z4', 29), ('Hồ', 'Mỹ A5', 30), ('Dương', 'Văn B5', 31), ('Hoàng', 'Thị C5', 32),
                                                              ('Nguyễn', 'Văn D5', 1), ('Trần', 'Thị E5', 2), ('Lê', 'Minh F5', 3), ('Phạm', 'Anh G5', 4),
                                                              ('Huỳnh', 'Thị H5', 5), ('Vũ', 'Quốc I5', 6), ('Đặng', 'Thị K5', 7), ('Bùi', 'Văn L5', 8),
                                                              ('Đỗ', 'Mỹ M5', 9), ('Hồ', 'Văn N5', 10), ('Dương', 'Thị O5', 11), ('Hoàng', 'Văn P5', 12),
                                                              ('Nguyễn', 'Quang Q5', 13), ('Trần', 'Thị R5', 14), ('Lê', 'Văn S5', 15), ('Phạm', 'Thị T5', 16),
                                                              ('Huỳnh', 'Minh U5', 17), ('Vũ', 'Thị V5', 18), ('Đặng', 'Văn W5', 19), ('Bùi', 'Thị X5', 20),
                                                              ('Đỗ', 'Quốc Y5', 21), ('Hồ', 'Mỹ Z5', 22), ('Dương', 'Văn A6', 23), ('Hoàng', 'Thị B6', 24),
                                                              ('Nguyễn', 'Văn C6', 25), ('Trần', 'Thị D6', 26), ('Lê', 'Minh E6', 27), ('Phạm', 'Anh F6', 28),
                                                              ('Huỳnh', 'Thị G6', 29), ('Vũ', 'Quốc H6', 30), ('Đặng', 'Thị I6', 31), ('Bùi', 'Văn K6', 32),
                                                              ('Đỗ', 'Mỹ L6', 1), ('Hồ', 'Văn M6', 2), ('Dương', 'Thị N6', 3), ('Hoàng', 'Văn O6', 4),
                                                              ('Nguyễn', 'Quang P6', 5), ('Trần', 'Thị Q6', 6), ('Lê', 'Văn R6', 7), ('Phạm', 'Thị S6', 8),
                                                              ('Huỳnh', 'Minh T6', 9), ('Vũ', 'Thị U6', 10), ('Đặng', 'Văn V6', 11), ('Bùi', 'Thị W6', 12),
                                                              ('Đỗ', 'Quốc X6', 13), ('Hồ', 'Mỹ Y6', 14), ('Dương', 'Văn Z6', 15), ('Hoàng', 'Thị A7', 16),
                                                              ('Nguyễn', 'Văn B7', 17), ('Trần', 'Thị C7', 18), ('Lê', 'Minh D7', 19), ('Phạm', 'Anh E7', 20),
                                                              ('Huỳnh', 'Thị F7', 21), ('Vũ', 'Quốc G7', 22), ('Đặng', 'Thị H7', 23), ('Bùi', 'Văn I7', 24),
                                                              ('Đỗ', 'Mỹ K7', 25), ('Hồ', 'Văn L7', 26), ('Dương', 'Thị M7', 27), ('Hoàng', 'Văn N7', 28),
                                                              ('Nguyễn', 'Quang O7', 29), ('Trần', 'Thị P7', 30), ('Lê', 'Văn Q7', 31), ('Phạm', 'Thị R7', 32),
                                                              ('Huỳnh', 'Minh S7', 1), ('Vũ', 'Thị T7', 2), ('Đặng', 'Văn U7', 3), ('Bùi', 'Thị V7', 4),
                                                              ('Đỗ', 'Quốc W7', 5), ('Hồ', 'Mỹ X7', 6), ('Dương', 'Văn Y7', 7), ('Hoàng', 'Thị Z7', 8),
                                                              ('Nguyễn', 'Văn A8', 9), ('Trần', 'Thị B8', 10), ('Lê', 'Minh C8', 11), ('Phạm', 'Anh D8', 12),
                                                              ('Huỳnh', 'Thị E8', 13), ('Vũ', 'Quốc F8', 14), ('Đặng', 'Thị G8', 15), ('Bùi', 'Văn H8', 16),
                                                              ('Đỗ', 'Mỹ I8', 17), ('Hồ', 'Văn K8', 18), ('Dương', 'Thị L8', 19), ('Hoàng', 'Văn M8', 20),
                                                              ('Nguyễn', 'Quang N8', 21), ('Trần', 'Thị O8', 22), ('Lê', 'Văn P8', 23), ('Phạm', 'Thị Q8', 24),
                                                              ('Huỳnh', 'Minh R8', 25), ('Vũ', 'Thị S8', 26), ('Đặng', 'Văn T8', 27), ('Bùi', 'Thị U8', 28),
                                                              ('Đỗ', 'Quốc V8', 29), ('Hồ', 'Mỹ W8', 30), ('Dương', 'Văn X8', 31), ('Hoàng', 'Thị Y8', 32),
                                                              ('Nguyễn', 'Văn Z8', 1), ('Trần', 'Thị A9', 2), ('Lê', 'Minh B9', 3), ('Phạm', 'Anh C9', 4),
                                                              ('Huỳnh', 'Thị D9', 5), ('Vũ', 'Quốc E9', 6), ('Đặng', 'Thị F9', 7), ('Bùi', 'Văn G9', 8),
                                                              ('Đỗ', 'Mỹ H9', 9), ('Hồ', 'Văn I9', 10), ('Dương', 'Thị K9', 11), ('Hoàng', 'Văn L9', 12),
                                                              ('Nguyễn', 'Quang M9', 13), ('Trần', 'Thị N9', 14), ('Lê', 'Văn O9', 15), ('Phạm', 'Thị P9', 16),
                                                              ('Huỳnh', 'Minh Q9', 17), ('Vũ', 'Thị R9', 18), ('Đặng', 'Văn S9', 19), ('Bùi', 'Thị T9', 20);
